#!/bin/bash

set -e

if [ "$#" -ne 5 ]; then
    echo "./$0 install DEVICE HOSTNAME USERNAME PASSWORD"
    echo " Where DEVICE is the device where the operating system should be installed, e.g. /dev/sda."
    exit 1
fi

STEP=$1
DEVICE=$2
HOSTNAME=$3
USERNAME=$4
PASSWORD=$5

if [ "${STEP}" == "install" ]; then
    # Configure the SSD with btrfs.
    mkfs.btrfs -f -L ${HOSTNAME} ${DEVICE}
    mount ${DEVICE} /mnt
    cd /mnt
    btrfs subvolume create __active
    btrfs subvolume create __active/rootvol
    btrfs subvolume create __active/home
    btrfs subvolume create __active/var
    btrfs subvolume create __snapshots
    cd
    umount /mnt
    mount -o subvol=__active/rootvol ${DEVICE} /mnt
    mkdir /mnt/{home,var}
    mount -o subvol=__active/home ${DEVICE} /mnt/home
    mount -o subvol=__active/var ${DEVICE} /mnt/var

    # Bootstrap the operating system.
    wget -qO - "https://www.archlinux.org/mirrorlist/?country=US&protocol=http&ip_version=4&use_mirror_status=on" | \
        sed 's/^#Server/Server/' > /etc/pacman.d/mirrorlist
    pacstrap /mnt base base-devel
    genfstab -U -p /mnt >> /mnt/etc/fstab
    sed -i 's/relatime,ssd,space_cache/noatime,discard,ssd,autodefrag,compress=lzo,space_cache/' /mnt/etc/fstab
    mkdir /mnt/defvol
    printf "LABEL=${HOSTNAME} /mnt/defvol btrfs rw,noatime,discard,ssd,autodefrag,compress=lzo,space_cache 0 0" >> /mnt/etc/fstab
    cp -L -u `realpath $0` /mnt/root/bootstrap
    arch-chroot /mnt /bin/bash -c "/root/bootstrap chroot ${DEVICE} ${HOSTNAME} ${USERNAME} ${PASSWORD}"
    rm /mnt/root/bootstrap
    sync && umount -R /mnt
    shutdown -r now

elif [ "${STEP}" == "chroot" ]; then
    # Standard boostrapping setup.
    echo ${HOSTNAME} > /etc/hostname
    ln -sf /usr/share/zoneinfo/America/Denver /etc/localtime
    sed -i '/^#en_US.UTF-8/s/^#//' /etc/locale.gen
    locale-gen
    echo "LANG=en_US.UTF-8" > /etc/locale.conf
    echo "KEYMAP=us" > /etc/vconsole.conf
    echo "FONT=lat9w-16" >> /etc/vconsole.conf
    hwclock --systohc --utc
    systemctl enable dhcpcd.service

    # I know this fails due to btrfs weirdness.
    set +e; mkinitcpio -p linux; set -e

    # Configure non-root user.
    useradd -m -g wheel -s /bin/bash ${USERNAME}
    echo "root:${PASSWORD}" | chpasswd
    echo "${USERNAME}:${PASSWORD}" | chpasswd
    sed -i '/^# %wheel ALL=(ALL) ALL/s/^# //' /etc/sudoers

    # Configure bootloader.
    pacman --noconfirm -S grub
    grub-install --target=i386-pc --recheck ${DEVICE}
    grub-mkconfig -o /boot/grub/grub.cfg

    # Configure pacman for atlassian and yaourt.
    curl https://www.hipchat.com/keys/hipchat-linux.key | GNUPGHOME=/etc/pacman.d/gnupg gpg --import
    cat <<- 'EOF' >> /etc/pacman.conf
		[atlassian]
		SigLevel = PackageOptional DatabaseRequired TrustAll
		Server = http://downloads.hipchat.com/linux/arch/$arch
		[archlinuxfr]
		SigLevel = Never
		Server = http://repo.archlinux.fr/$arch
		EOF

    # Update the system and install several packages.
    pacman --noconfirm -Syyu
    pacman --noconfirm -S openssh
    pacman --noconfirm -S ttf-inconsolata
    pacman --noconfirm -S git
    pacman --noconfirm -S mercurial
    pacman --noconfirm -S gvim
    pacman --noconfirm -S sudo
    pacman --noconfirm -S xorg-server
    pacman --noconfirm -S xorg-xrandr
    pacman --noconfirm -S xorg-xinit
    pacman --noconfirm -S xorg-xdpyinfo
    pacman --noconfirm -S xorg-xrdb
    pacman --noconfirm -S xf86-video-nouveau
    pacman --noconfirm -S rxvt-unicode
    pacman --noconfirm -S i3
    pacman --noconfirm -S dmenu
    pacman --noconfirm -S alsa-utils
    pacman --noconfirm -S firefox
    pacman --noconfirm -S gstreamer0.10-base
    pacman --noconfirm -S gstreamer0.10
    pacman --noconfirm -S hipchat
    pacman --noconfirm -S yaourt

    # Stupid yaourt can't run as root. So run it as non-root but first change
    # sudoers so we can run it without a password. Undo that when we're done.
    echo "${USERNAME} ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
    sudo -u aaronj yaourt --noconfirm -S jre
    sudo -u aaronj yaourt --noconfirm -S spotify
    sudo -u aaronj yaourt --noconfirm -S start-stop-daemon
    sed -i "/${USERNAME}/d" /etc/sudoers

    # Distbox/chroot stuff.
    cd ~/
    cat <<- 'EOF' >> /etc/profile.d/solidfire.sh
		#!/bin/bash
		export PATH=$PATH:/bin:/sbin:/usr/sbin
		EOF
    chmod a+x /etc/profile.d/solidfire.sh
    pacman --noconfirm -S jq
    pacman --noconfirm -S distcc
    pacman --noconfirm -S xmlstarlet
    pacman --noconfirm -S pigz
    pacman --noconfirm -S wget
    pacman --noconfirm -S dnsutils
    pacman --noconfirm -S cronie
    pacman --noconfirm -S lsb-release
    groupadd crontab
    groupadd sshd
    useradd -g sshd -c 'sshd privsep' -d /var/empty -s /bin/false sshd 
    wget http://bdr-jenkins.eng.solidfire.net/libs/distfiles/bashutils-sfdev-0.7.9_amd64.tgz
    tar -C / -xvf bashutils-sfdev-0.7.9_amd64.tgz /usr
    rm bashutils-sfdev-0.7.9_amd64.tgz
    wget http://bdr-jenkins.eng.solidfire.net/libs/distfiles/bashutils-sfdev-0.8.11_amd64.tgz
    tar -C / -xvf bashutils-sfdev-0.8.11_amd64.tgz /usr
    rm bashutils-sfdev-0.8.11_amd64.tgz
    wget http://bdr-jenkins.eng.solidfire.net/libs/distfiles/bashutils-sfdev-0.8.12_amd64.tgz
    tar -C / -xvf bashutils-sfdev-0.8.11_amd64.tgz /usr
    rm bashutils-sfdev-0.8.12_amd64.tgz
    wget http://bdr-jenkins.eng.solidfire.net/libs/distfiles/murder-sfdev-0.1.2-p1_amd64.tgz
    tar -C / -xvf murder-sfdev-0.1.2-p1_amd64.tgz /usr/local/
    mv /usr/local/lib/python2.7/dist-packages/murder-0.1.2-p1 /usr/lib/python2.7/site-packages
    rm -rf /usr/local/lib/python2.7
    rm murder-sfdev-0.1.2-p1_amd64.tgz
    wget http://bdr-jenkins.eng.solidfire.net/libs/distfiles/distbox_1.7_amd64.tgz
    tar -C / -xvf distbox_1.7_amd64.tgz /etc/distbox
    tar -C / -xvf distbox_1.7_amd64.tgz /usr
    cp -r /usr/lib64/systemd /usr/lib
    rm -rf /usr/lib64
    rm distbox_1.7_amd64.tgz
    touch /etc/distbox/user.conf
    distbox install
    systemctl enable distbox.service

    # Configure ssh.
    systemctl enable sshd.socket
    su -c "mkdir ~/.ssh" ${USERNAME}
    su -c "cd ~/.ssh && wget http://bdr-jenkins.eng.solidfire.net/keys/solidfire_dev_rsa.pub" ${USERNAME}
    su -c "cd ~/.ssh && wget http://bdr-jenkins.eng.solidfire.net/keys/solidfire_dev_rsa" ${USERNAME}
    su -c "chmod 600 ~/.ssh/solidfire_dev_rsa" ${USERNAME}
    cat <<- EOF >> /home/${USERNAME}/.ssh/config
		Host ${HOSTNAME} ${HOSTNAME}.corp.solidfire.net
		    ForwardX11 yes
		    ForwardX11Trusted yes
		    User ${USERNAME}
		
		# Kiln
		Host solidfire.kilnhg.com
		    IdentityFile ~/.ssh/kiln_rsa
		
		# Clients to possibly run GUI apps on
		Host 192.168.135.* 172.26.75.* 172.26.8?.* 172.16.15?.*
		    ForwardX11 yes
		    ForwardX11Trusted yes
		    User root
		    IdentityFile ~/.ssh/solidfire_dev_rsa
		
		# Options for SolidFire nodes
		Host 192.168.133.* 172.26.65.* 192.168.139.* 172.24.65.* 172.24.58.* 172.30.65.*
		    User sfadmin
		    IdentityFile ~/.ssh/solidfire_dev_rsa
		
		# Options for all hosts
		Host *
		    AddressFamily inet
		    CheckHostIp no
		    Cipher arcfour256
		    ConnectTimeout 20
		    ConnectionAttempts 1
		    GSSAPIAuthentication no
		    HashKnownHosts no
		    ServerAliveInterval 60
		    ServerAliveCountMax 6
		    StrictHostKeyChecking no
		    TCPKeepAlive yes
		    UserKnownHostsFile /dev/null
		    User root
		    ForwardX11 no
		    ForwardX11Trusted no
		EOF
    chmod 664 /home/${USERNAME}/.ssh/config

    # Do some vim configuration.
    su -c "mkdir -p ~/.vim/autoload ~/.vim/bundle" ${USERNAME}
    su -c "curl -LSso ~/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim" ${USERNAME}
    su -c "cd ~/.vim/bundle && git clone git://github.com/tpope/vim-sensible.git" ${USERNAME}
    su -c "cd ~/.vim/bundle && git clone git://github.com/altercation/vim-colors-solarized.git" ${USERNAME}

    # Prepare some config files.
    cat <<- 'EOF' >> /etc/modprobe.d/nobeep.conf
		blacklist pcspkr
		EOF

    cat <<- 'EOF' >> /home/${USERNAME}/.bash_profile
		[[ -z $DISPLAY && $XDG_VTNR -eq 1 ]] && exec startx
		EOF

    cat <<- 'EOF' >> /etc/X11/xorg.conf.d/20-nouveau.conf
		Section "Monitor"
		    Identifier "DellLeft"
		    Option "PreferredMode" "26x0x1600_60.00"
		    DisplaySize 641 402
		EndSection

		Section "Monitor"
		    Identifier "DellRight"
		    Option "PreferredMode" "26x0x1600_60.00"
		    Option "LeftOf" "DellLeft"
		    DisplaySize 641 402
		EndSection

		Section "Device"
		    Identifier "nvidia card"
		    Driver "nouveau"
		    Option "Monitor-DVI-D-1" "DellLeft"
		    Option "Monitor-DVI-I-1" "DellRight"
		EndSection

		Section "Screen"
		    Identifier "screen1"
		    Monitor "DellLeft"
		    DefaultDepth 24
		    SubSection "Display"
		        Depth 24
		        Virtual 2560 1600
		    EndSubSection
		    Device "nvidia card"
		EndSection

		Section "ServerLayout"
		    Identifier "layout1"
		    Screen "screen1"
		EndSection
		EOF

    cat <<- 'EOF' >> /home/${USERNAME}/.vimrc
		set nocompatible
		set t_Co=16
		call pathogen#infect()
		syntax on
		set background=dark
		colorscheme solarized
		filetype plugin indent on
		set shiftwidth=4
		set tabstop=4
		set expandtab
		set number
		set cursorline
		set hlsearch
		EOF
    chown aaronj:wheel /home/${USERNAME}/.vimrc

    cat <<- 'EOF' >> /home/${USERNAME}/.xinitrc
		xrdb -merge ~/.Xresources
		exec i3
		EOF
    chown aaronj:wheel /home/${USERNAME}/.xinitrc

    cat <<- 'EOF' >> /home/${USERNAME}/.Xresources
		#define S_yellow        #b58900
		#define S_orange        #cb4b16
		#define S_red           #dc322f
		#define S_magenta       #d33682
		#define S_violet        #6c71c4
		#define S_blue          #268bd2
		#define S_cyan          #2aa198
		#define S_green         #859900

		! Dark
		#define S_base03        #002b36
		#define S_base02        #073642
		#define S_base01        #586e75
		#define S_base00        #657b83
		#define S_base0         #839496
		#define S_base1         #93a1a1
		#define S_base2         #eee8d5
		#define S_base3         #fdf6e3

		! Light
		! #define S_base03        #fdf6e3
		! #define S_base02        #eee8d5
		! #define S_base01        #93a1a1
		! #define S_base00        #839496
		! #define S_base0         #657b83
		! #define S_base1         #586e75
		! #define S_base2         #073642
		! #define S_base3         #002b36

		URxvt*background:              S_base03
		URxvt*foreground:              S_base0
		URxvt*fading:                  40
		URxvt*fadeColor:               S_base03
		URxvt*cursorColor:             S_base1
		URxvt*pointerColorBackground:  S_base01
		URxvt*pointerColorForeground:  S_base1

		URxvt*color0:                  S_base02
		URxvt*color1:                  S_red
		URxvt*color2:                  S_green
		URxvt*color3:                  S_yellow
		URxvt*color4:                  S_blue
		URxvt*color5:                  S_magenta
		URxvt*color6:                  S_cyan
		URxvt*color7:                  S_base2
		URxvt*color8:                  S_base03
		URxvt*color9:                  S_orange
		URxvt*color10:                 S_base01
		URxvt*color11:                 S_base00
		URxvt*color12:                 S_base0
		URxvt*color13:                 S_violet
		URxvt*color14:                 S_base1
		URxvt*color15:                 S_base3

		! urxvt
		URxvt*buffered: true
		URxvt*cursorBlink: true
		URxvt*underlineColor: yellow
		URxvt*font:  xft:inconsolata:size=12:antialias=true
		URxvt*depth: 32
		URxvt*borderless: 1
		URxvt*scrollBar: false
		URxvt*loginShell: true
		Urxvt*secondaryScroll:  true    # Enable Shift-PageUp/Down in screen
		URxvt*saveLines: 50000
		URxvt*termName: rxvt-unicode
		URxvt.perl-ext-common: default
		URxvt.matcher.button: 1
		URxvt.intensityStyles: false
		EOF
    chown aaronj:wheel /home/${USERNAME}/.Xresources
fi
